[package]
name = "bitcoin"
version = "0.1.0"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]
edition = "2018"

[dependencies]
yansi = "0.5"
promptly = "0.1.5"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
reqwest = "0.9.11"
chrono = "0.4.6"
atty = "0.2.11"
